site_name: airbreak
repo_url: https://github.com/osresearch/airbreak/
edit_uri: ""
theme:
  name: cyborg
  custom_dir: docs/custom/
extra_css: [extra.css]
markdown_extensions:
        - admonition
site_favicon: favicon.ico
nav:
        - Guide:
                - About: 'index.md'
                - Disassembly: 'disassembly.md'
                - Firmware: 'firmware.md'
                - Evaluation: 'evaluation.md'
        - Information:
                - Hardware:
                        - Datasheets: 'info/datasheets.md'
                        - Pinouts: 'info/pinouts.md'
                        - Useful Test Points: 'info/testpoints.md'
                - Software:
                        - OpenOCD Scripts: 'info/tcl.md'
                        - Windows Setup Instructions: 'info/windows.md'
                - Firmware:
                        - Documentation: 'info/firmware-docs.md'
                        - Development: 'info/extensions.md'
