site_name: airbreak
repo_url: https://github.com/osresearch/airbreak/
edit_uri: ""
theme:
  name: flatly
  custom_dir: docs/custom/
markdown_extensions:
        - admonition
nav:
        - Guide:
                - About: 'index.md'
                - Disassembly: 'disassembly.md'
                - Firmware: 'firmware.md'
        - Information:
                - Hardware:
                        - Airsense S10 Hardware: 'info/hardware.md'
                        - Pinouts: 'info/pinouts.md'
                        - Useful Test Points: 'info/testpoints.md'
                - Software:
                        - OpenOCD Scripts: 'info/tcl.md'
                        - Windows Setup Instructions: 'info/windows.md'
                - Firmware:
                        - Documentation: 'info/firmware-docs.md'
                        - Development: 'info/extensions.md'
